### ISSUE TITLE
error breakpoint file

### ISSUE THREAD

**Issue by guillaume-rs** [bioinform/breakseq2#14]
Hello,

I'm trying to use Breakseq2 to detect structural variants on my data.

Unfortunately I'm not working on human data, and then, cannot use the breakpoint library given in parameters. ( http://bioinform.github.io/breakseq2/)

When I try to use the programme without this parameter I have the following message :

" Atleast one of the breakpoint FASTA or GFF must be specified ", and it doesn't work either with an empty file.

Would you know a way of using Breakseq2 without giving a breakpoint library file?

Thanks

Guillaume

**Comment by marghoob** [comment]
Hi @guillaume-rs the BreakSeq2 algorithm is based on matching reads to known junction sequences (corresponding to known SVs). So, without a breakpoint library, BreakSeq2 cannot work.
