### ISSUE TITLE
breakseq2 breaks at breakseq_core

### ISSUE THREAD

**Issue by burnsro** [bioinform/breakseq2#16]
I installed breakseq2 using a virtualenv in python 
I using am using Python 2.7.12,  Pysam 0.10.0 and Biopython 1.68 SAMtools 0.1.19 and BWA 0.7.1.15

I export the PYTHONPATH to breakseq2-2.2/lib/python
then I ran 
python breakseq2-2.2/bin/run_breakseq2.py --reference ${ref} --bams ${bam} --work ${work} --bwa ${bwa} --samtools ${samtools} --bplib ${fasta} --nthreads 4 --keep_temp --window 100 --junction_length 200 --min_span 10 --chromosomes chr1

and the bam is processed up until breakseq_core 
INFO 2018-05-01 18:55:09,652 parallel_preprocess_and_align Finished parallel preprocess and align (88.0841 s).
INFO 2018-05-01 18:55:09,654 breakseq_core        Processing final.bam
Traceback (most recent call last):
  File "build/scripts-2.7/run_breakseq2.py", line 28, in <module>
    args.keep_temp, args.window, args.junction_length))
  File "build/bdist.linux-x86_64/egg/breakseq2/breakseq_top.py", line 121, in breakseq2_workflow
  File "build/bdist.linux-x86_64/egg/breakseq2/breakseq_core.py", line 63, in breakseq_core
ValueError: need more than 3 values to unpack

and tells me it breaks at line 28 for args.keep_temp, args.window, args.junction_length (which I tried with specifying and without specifying)
I can only tell python is trying to split something that is not working?

**Comment by marghoob** [comment]
Hi @burnsro what breakpoint library are you using? It looks like some of the junction names in the breakpoint library do not have enough fields. If you point me to the location where you pulled the breakpoint library from, that would help figure out and fix the problem more clearly.

**Comment by burnsro** [comment]
Ah I see you are exactly right, I made the breakpoint library fasta using bedtools but didn't add the extra columns needed
