### ISSUE TITLE
ERROR at preprocess_and_align step

### ISSUE THREAD

**Issue by boboppie** [bioinform/breakseq2#8]
Dear @marghoob ,

I'm trying to run breakseq2 on a whole genome bam. My command is like:

```
$ run_breakseq2.py --nthreads 2 --reference $REF --bams /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam --bplib /scratch/cbrc/tmp/
fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna --bwa $bwa_HOME/bin --samtools $samtools_HOME/bin
```

The error message:

```
ERROR 2015-05-12 16:06:53,924 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/home/cbrcmod/scratch/modules/out/modulebin/breakseq2/2.0/lib/python2.7/site-packages/breakseq2/preprocess_and_align.py", line 35, in preprocess_and_align
    subprocess.check_call(bash_cmd, shell=True, stderr=logfd)
  File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"' returned non-zero exit status 126
()
```

The programme is still running, is this something I need to worry about?

Best wishes,
Fengyuan

**Comment by marghoob** [comment]
Hi Fengyuan,

Please try running

bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin samse
/scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna
<(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin aln
/scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna
/scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq)
/scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq |
/scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin view -S -
-1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"

and let me know what you get. It looks like the bash command is
failing for some reason. breakseq2 may still run while waiting for
some processing threads to finish. In this case, the processing thread
failed.

Marghoob.


On Tue, May 12, 2015 at 8:21 AM, Fengyuan Hu <notifications@github.com>
wrote:

> Dear @marghoob <https://github.com/marghoob> ,
>
> I'm trying to run breakseq2 on a whole genome bam. My command is like:
>
> $ run_breakseq2.py --nthreads 2 --reference $REF --bams /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam --bplib /scratch/cbrc/tmp/
> fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna --bwa $bwa_HOME/bin --samtools $samtools_HOME/bin
>
> The error message:
>
> ERROR 2015-05-12 16:06:53,924 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Caught exception in worker thread
> Traceback (most recent call last):
>   File "/home/cbrcmod/scratch/modules/out/modulebin/breakseq2/2.0/lib/python2.7/site-packages/breakseq2/preprocess_and_align.py", line 35, in preprocess_and_align
>     subprocess.check_call(bash_cmd, shell=True, stderr=logfd)
>   File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command 'bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"' returned non-zero exit status 126
> ()
>
> The programme is still running, is this something I need to worry about?
>
> Best wishes,
> Fengyuan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioinform/breakseq2/issues/8>.
>



-- 

<http://www.bina.com>

*Marghoob Mohiyuddin, PhD  *//  Sr. Bioinformatics Scientist, Bina
Technologies, part of Roche Sequencing
E. marghoob@bina.com

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://f1000.com/posters/search?query=bina+technologies>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>
*Test Drive Bina  //  Experience NextGen analysis for yourself *
<http://www.bina.com/test-drive.html>

**Comment by boboppie** [comment]
Hi Marghoob,

Thanks for the suggestion! I think I've figured out where went wrong. When specifying the paths to bwa and samtools, I should include the programme name like "**--bwa $bwa_HOME/bin/bwa --samtools $samtools_HOME/bin/samtools**" instead of only giving the directories which contains the programmes.

Best wishes,
Fengyuan

**Comment by boboppie** [comment]
Hi Marghoob,

I have to re-open this ticket as I'm still getting the error messages:

```
ERROR 2015-05-12 17:06:29,151 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/home/cbrcmod/scratch/modules/out/modulebin/breakseq2/2.0/lib/python2.7/site-packages/breakseq2/preprocess_and_align.py", line 35, in preprocess_and_align
    subprocess.check_call(bash_cmd, shell=True, stderr=logfd)
  File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin/samtools view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"' returned non-zero exit status 1
()
INFO 2015-05-12 17:06:29,185 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Extracting candidate reads from /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam for chromosome 3 and aligning against /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cbrcmod/scratch/modules/out/modulebin/python/2.7.7/lib64/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
```

Here is the output of the command you suggested to run:

```
% bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin/samtools view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_sai2sam_se] fail to locate the index
[bwa_aln] fail to locate the index
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
```

Bw,
Fengyuan

**Comment by boboppie** [comment]
Hi Marghoob,

I believe the error was caused by the missing index of the breakpoint fasta (I downloaded from http://sv.gersteinlab.org/phase1bkpts/breakseq2_bplib_20150129.zip). After creating the index, it's running and finished now.

A couple of things I've noticed:

1. I specified chrY, but output vcf includes calls for all chromosomes.
2. In the 4th INFO line, chromosome name is empty.

```bash
% run_breakseq2.py --reference $REF --bams /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam --chromosomes Y --bplib /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna --bwa /home/cbrcmod/scratch/modules/out/modulebin/bwa/0.7.12/bin/bwa --samtools /home/cbrcmod/scratch/modules/out/modulebin/samtools/0.1.19/bin/samtools
INFO 2015-05-13 14:21:51,228 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Extracting candidate reads from /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam for chromosome Y and aligning against /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna
INFO 2015-05-13 14:23:27,876 print_candidate_reads-<Process(PoolWorker-1, started daemon)> Extracted 341102 reads from BAMs /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam
INFO 2015-05-13 14:23:27,876 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Running bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin/samtools view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/0.bam"
INFO 2015-05-13 14:23:40,156 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Extracting candidate reads from /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam for chromosome  and aligning against /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna
INFO 2015-05-13 14:28:23,583 print_candidate_reads-<Process(PoolWorker-1, started daemon)> Extracted 37240480 reads from BAMs /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam
INFO 2015-05-13 14:28:23,584 preprocess_and_align-<Process(PoolWorker-1, started daemon)> Running bash -c "/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa samse /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna <(/scratch/cbrcmod/modules/out/modulebin/bwa/0.7.12/bin/bwa aln /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/data/breakseq2_bplib_20150129.fna /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/1.fq) /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/1.fq | /scratch/cbrcmod/modules/out/modulebin/samtools/0.1.19/bin/samtools view -S - -1 -F 4 -bo /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/1.bam"
INFO 2015-05-13 14:40:52,464 breakseq_core        Processing /scratch/cbrc/tmp/fh293/cnv-WGS/experiment/breakseq2/work/final.bam
```

Bw,
Fengyuan

**Comment by marghoob** [comment]
Thanks @boboppie for trying out breakseq2. The empty chromosome name is used for unmapped reads. I will fix the filter for only reporting calls on the specified chromosomes.

**Comment by boboppie** [comment]
Hi @marghoob ,

Thank you for the support!

Another question is that is there an advance to use multiple samples? Will it improve the quality of the calls?

Bw,
Fengyuan

**Comment by marghoob** [comment]
BreakSeq2 does not support multiple samples right now. I don't think BreakSeq2 needs to do that, however. It can be done as a separate step after BreakSeq2--kind of like GATK's single-sample HaplotypeCaller with GVCF output followed by GenotypeGVCFs for joint-calling.
